apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-ci-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: kisese/node-ci
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-ci-service
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 32121
  selector:
    app: helloworld